-- ====================================================================
-- CEFC SARL — SCHEMA SUPABASE & ROW LEVEL SECURITY (RLS)
-- ====================================================================
-- Ce script crée les tables pour stocker les rendez-vous et les devis
-- et active le Row Level Security (RLS) pour une sécurité maximale.
--
-- INSTRUCTIONS D'EXÉCUTION :
-- 1. Rendez-vous sur votre tableau de bord Supabase (https://supabase.com/dashboard)
-- 2. Ouvrez votre projet "Site Web CEFC SARL"
-- 3. Dans le menu de gauche, cliquez sur "SQL Editor"
-- 4. Cliquez sur "New query", collez l'intégralité de ce script et cliquez sur "Run"
-- ====================================================================

-- 1. Table des Rendez-vous (appointments)
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT DEFAULT 'Non renseigné',
    company TEXT DEFAULT 'Non renseignée',
    service TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'cabinet',
    notes TEXT DEFAULT 'Aucune note',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table des Demandes de Devis (quotes)
CREATE TABLE IF NOT EXISTS public.quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT DEFAULT 'Non renseigné',
    company TEXT DEFAULT 'Non renseignée',
    service TEXT NOT NULL,
    message TEXT DEFAULT 'Aucun message',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ====================================================================
-- 3. ACTIVATION DU ROW LEVEL SECURITY (RLS)
-- ====================================================================
-- Lorsque le RLS est activé, TOUT ACCÈS EST BLOQUÉ PAR DÉFAUT (Zero-Trust)
-- à moins qu'une politique explicite ne soit définie.

ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- Suppression des politiques existantes pour éviter les doublons lors de ré-exécutions
DROP POLICY IF EXISTS "Autoriser insertion publique des RDVs" ON public.appointments;
DROP POLICY IF EXISTS "Autoriser insertion publique des Devis" ON public.quotes;
DROP POLICY IF EXISTS "Lecture reservee aux administrateurs" ON public.appointments;
DROP POLICY IF EXISTS "Lecture reservee aux administrateurs" ON public.quotes;

-- RÈGLE A : Permettre aux visiteurs (anon & authenticated) de SOUMETTRE (INSERT uniquement)
-- Les clients peuvent remplir le formulaire, mais JAMAIS lire les données d'autrui !
CREATE POLICY "Autoriser insertion publique des RDVs"
ON public.appointments
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Autoriser insertion publique des Devis"
ON public.quotes
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- RÈGLE B : Lecture, Modification et Suppression
-- IMPORTANT : Par défaut sans politique SELECT, personne avec la clé anon ne peut lire !
-- Seul le 'service_role' (utilisé par votre serveur Node.js backend) ou les admins connectés
-- ont un accès complet en lecture / écriture.

-- Index de performance pour les recherches rapides
CREATE INDEX IF NOT EXISTS idx_appointments_created_at ON public.appointments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotes_created_at ON public.quotes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_phone ON public.appointments(phone);
CREATE INDEX IF NOT EXISTS idx_quotes_phone ON public.quotes(phone);
